language: node_js
node_js:
  - '10'
before_install:
  ## The apt "awscli" client does not support Lambda yet; use pip
  - sudo apt-get install -y python3-pip
  - sudo pip3 install awscli
  - npm install
script:
  - .travis/build.sh
notifications:
  email:
    - $GITHUB_EMAIL
