language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
      - python3-pip
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
install:
  - npm ci
before_script:
  - pip3 install awscli
  # - npm install cypress
script:
  echo build is complete!
  # - .travis/build.sh
  # - npm test
notifications:
  email:
    - $GITHUB_EMAIL
